apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  namespace: default
  annotations:
    # Especificar Traefik como Ingress Controller
    kubernetes.io/ingress.class: traefik
    # Middleware para remover el prefijo de la ruta antes de enviar al backend
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-prefix@kubernetescrd
spec:
  rules:
  # Regla para acceder a las aplicaciones a travÃ©s del Load Balancer
  - http:
      paths:
      # Ruta para App1
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-service
            port:
              number: 80
      # Ruta para App2
      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: app2-service
            port:
              number: 80
---
# Middleware de Traefik para remover el prefijo de la ruta
# Esto convierte /app1/algo -> /algo antes de llegar al servicio
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /app1
      - /app2
    forceSlash: false
